package com.sora.splineroads.world;
import com.sora.splineroads.core.*;
import com.sora.splineroads.core.RoadGeometry.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraftforge.gametest.*;
import java.util.*;
@GameTestHolder("splineroads_lane_v2") @PrefixGameTestTemplate(false)
public final class LaneRampV2GameTests {
 static RoadRecord road(GameTestHelper h,int x,int z,int dx,int dz,int y,Style style){var a=Revision32GameTests.marker(h,x,y,z,RoadPlanner.yaw(new V(dx,0,dz).horizontalUnit()));var b=Revision32GameTests.marker(h,x+dx,y,z+dz,RoadPlanner.yaw(new V(dx,0,dz).horizontalUnit()));return RoadData.get(h.getLevel()).connect(h.getLevel(),null,a,b,new Settings(Mode.STRAIGHT,style,RoadProfile.width(style,RoadProfile.Options.DEFAULT,4),1,.35,90).structure(Structure.AUTO),null);}
 static RoadRecord current(RoadData d,RoadRecord r){return d.index.roads.get(r.id()).record;}
 static LanePoints.Point manual(GameTestHelper h,RoadRecord r,double station,int lane){var at=LanePoints.lane(r.mesh(),station,lane).position();return LanePointTool.create(h.getLevel(),null,r.id(),at);}
 static RoadRecord ramp(GameTestHelper h,RoadRecord a,LanePoints.Point p,RoadRecord b,LanePoints.Point q,LanePoints.Path path,boolean source,boolean target){var d=RoadData.get(h.getLevel());System.out.println("LANE BUILD "+path+" "+p.position()+" -> "+q.position());var link=new LanePoints.Link(LanePoints.Ref.lane(a.id(),p.id()),LanePoints.Ref.lane(b.id(),q.id()),new LanePoints.Options(path,source,target,24,32),null);var r=LaneRamps.generate(d,LaneTopology.records(d),UUID.randomUUID(),new UUID(0,0),link);if(path==LanePoints.Path.LEFT_LOOP)for(var sample:r.mesh().samples())for(int xx=-1;xx<=1;xx++)for(int zz=-1;zz<=1;zz++){var foot=BlockPos.containing(sample.center().x()+xx,200,sample.center().z()+zz);h.getLevel().getChunkAt(foot);h.getLevel().setBlock(foot,net.minecraft.world.level.block.Blocks.STONE.defaultBlockState(),2);}LaneRamps.build(d,h.getLevel(),null,r);return current(d,r);}
 static void check(GameTestHelper h,boolean v,String message){h.assertTrue(v,message);}
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=24000)
 public static void pointOnlyChangesPreserveWorldAndCollision(GameTestHelper h){
  var l=h.getLevel();var d=RoadData.get(l);var host=road(h,198000,198000,0,200,220,Style.O6_RAIL);
  var initial=d.index.roads.get(host.id());var collision=initial.prepareCollision();long revision=d.index.revision();var shapes=initial.mesh.samples();var structures=initial.record.structures();
  long start=System.nanoTime();var points=new ArrayList<LanePoints.Point>();
  for(int i=0;i<12;i++)points.add(manual(h,current(d,host),10+i*12,2));
  double millis=(System.nanoTime()-start)/1e6;System.out.println("POINT METADATA: 12 creations in "+millis+" ms");
  var latest=d.index.roads.get(host.id());check(h,d.index.revision()==revision,"point creation does not invalidate geometry or chunk shapes");check(h,latest.prepareCollision()==collision,"point creation reuses exact collision index");check(h,latest.mesh.samples()==shapes&&latest.record.structures().equals(structures),"all road samples and furniture remain unchanged");
  var p=points.get(3);var command=new CompoundTag();command.putUUID("Id",host.id());command.putUUID("Point",p.id());command.putInt("Signature",latest.record.header().hashCode());command.putInt("Lane",5);LanePointTool.edit(l,null,command);
  var moved=LaneTopology.point(current(d,host),p.id());check(h,moved.anchor().equals(p.anchor())&&moved.lane()==5,"unreferenced opposite-lane edit preserves anchor");check(h,d.index.revision()==revision,"unreferenced lane edit remains metadata only");
  command.putInt("Signature",current(d,host).header().hashCode());command.putBoolean("Delete",true);LanePointTool.edit(l,null,command);check(h,d.index.revision()==revision&&LaneTopology.metadata(current(d,host)).points().stream().noneMatch(v->v.id().equals(p.id())),"unreferenced delete immediately removes only the marker");
  var saved=d.save(new CompoundTag());var again=RoadData.load(saved);check(h,LaneTopology.metadata(current(d,host)).equals(LaneTopology.metadata(again.index.roads.get(host.id()).record)),"point metadata persists without a road rebuild");h.succeed();
 }
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=24000)
 public static void tightRightTurnCanPreviewAndBuild(GameTestHelper h){
  var l=h.getLevel();var d=RoadData.get(l);int x=199000,z=199000;
  var a=road(h,x+100,z,-100,0,220,Style.O1_ONE);var b=road(h,x-140,z-40,0,-100,220,Style.O1_ONE);
  var p=LaneTopology.metadata(current(d,a)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_END).findFirst().orElseThrow();var q=LaneTopology.metadata(current(d,b)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_START).findFirst().orElseThrow();
  var r=ramp(h,current(d,a),p,current(d,b),q,LanePoints.Path.RIGHT,false,false);check(h,r.mesh().length()<240&&!d.index.roads.get(r.id()).cells.isEmpty(),"short genuine right turn builds real collision");
  check(h,LaneTopology.metadata(r).link().from().point().equals(p.id())&&LaneTopology.metadata(r).link().to().point().equals(q.id()),"right turn keeps exact selected points");h.succeed();
 }
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=24000)
 public static void legacyCurvedRoadCannotPoisonUpdatesOrPlacement(GameTestHelper h){
  var l=h.getLevel();var d=RoadData.get(l);int x=196000,z=196000;
  var a=Revision32GameTests.marker(h,x,220,z,0);var b=Revision32GameTests.marker(h,x+100,220,z+180,-90);
  var s=new Settings(Mode.CURVE,Style.O6_RAIL,26,1,.4,90).structure(Structure.GROUND);
  var curve=new RoadRecord(UUID.randomUUID(),new UUID(0,0),a,b,RoadData.requireNode(l,a,null).node(),RoadData.requireNode(l,b,null).node(),s,false,4).caps(3);
  var c=Revision32GameTests.marker(h,x+400,220,z,-90);var e=Revision32GameTests.marker(h,x+480,220,z,-90);
  var straight=new RoadRecord(UUID.randomUUID(),new UUID(0,0),c,e,RoadData.requireNode(l,c,null).node(),RoadData.requireNode(l,e,null).node(),new Settings(Mode.STRAIGHT,Style.O6_RAIL,26,1,.4,90).structure(Structure.GROUND),false,4).caps(3);
  var root=new CompoundTag();root.putInt("Version",30);var roads=new ListTag();
  for(var r:List.of(curve,straight)){var tag=r.save();tag.getCompound("Settings").remove("LanePointsV2");roads.add(tag);}root.put("Roads",roads);
  var loaded=RoadData.load(root);loaded.index.roads.values().forEach(v->d.index.put(RoadIndex.Built.loading(v.record)));
  check(h,!LaneTopology.needsRefresh(d.index.roads.values()),"legacy curved automatic endpoints are canonical at load");
  var updated=d.connect(l,null,c,e,straight.settings().options(straight.settings().options().hideArrows(true)),straight.id());
  check(h,updated.id().equals(straight.id()),"unrelated old straight road can be updated with legacy curve present");
  for(var host:List.of(current(d,curve),current(d,straight))){
   var selected=LanePoints.lane(host.mesh(),host.mesh().length()*.6,2);V hit=selected.position().add(RoadStructures.sample(host.mesh(),selected.station()).left().mul(1.3));
   var p=LanePointTool.create(l,null,host.id(),hit);var actual=LaneTopology.point(current(d,host),p.id());
   check(h,actual.anchor()!=null&&actual.position().distance(LanePoints.lane(current(d,host).mesh(),actual).position())<1e-7,"off-center click creates exact lane-center point on legacy road");
   check(h,actual.position().distance(hit)>.9,"click position is not an arbitrary attached-point coordinate");
   var duplicate=LanePointTool.create(l,null,host.id(),actual.position());check(h,duplicate.id().equals(actual.id()),"repeated center click keeps existing point identity");
  }
  var saved=d.save(new CompoundTag());var again=RoadData.load(saved);check(h,saved.getInt("Version")==34,"new save version records lane sections and longitudinal anchors");
  for(var host:List.of(curve,straight))check(h,LaneTopology.metadata(current(d,host)).equals(LaneTopology.metadata(again.index.roads.get(host.id()).record)),"save/load retains canonical points and IDs");
  check(h,!LaneTopology.needsRefresh(d.index.roads.values()),"world stays stable after old-road edits and point creation");h.succeed();
 }
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=24000)
 public static void legacyManualCenterMigrationAndRampReset(GameTestHelper h){
  var l=h.getLevel();var d=RoadData.get(l);var host=road(h,197000,197000,0,120,220,Style.O4_YELLOW);
  var selected=LanePoints.lane(host.mesh(),40,2);var off=new LanePoints.Point(UUID.randomUUID(),LanePoints.Origin.MANUAL,2,selected.position().add(new V(1,0,0)));
  var old=current(d,host).withLanePoints(LaneTopology.metadata(current(d,host)).points(List.of(off)));
  var root=new CompoundTag();root.putInt("Version",31);var roads=new ListTag();roads.add(old.save());root.put("Roads",roads);var loaded=RoadData.load(root);var restored=loaded.index.roads.get(host.id()).record;
  var p=LaneTopology.point(restored,off.id());check(h,p.origin()==LanePoints.Origin.MANUAL&&p.lane()==2&&p.anchor()!=null,"legacy manual point migrates without changing identity or lane");
  check(h,p.position().distance(selected.position())<1e-7,"legacy off-center coordinate is corrected to lane axis");
  var stack=new net.minecraft.world.item.ItemStack(com.sora.splineroads.SplineRoads.RAMP_CONNECTOR.get());var tag=stack.getOrCreateTag();tag.put("LaneFrom",LanePointCodec.ref(LanePoints.Ref.lane(host.id(),p.id())));tag.put("LaneTo",tag.getCompound("LaneFrom").copy());tag.putUUID("LanePreview",UUID.randomUUID());tag.putString("LaneDimension","minecraft:overworld");tag.putString("Unrelated","keep");
  LaneRampTool.clearSelection(stack);check(h,!tag.contains("LaneFrom")&&!tag.contains("LaneTo")&&!tag.contains("LanePreview")&&!tag.contains("LaneDimension"),"reset drops all selections and preview token");check(h,tag.getString("Unrelated").equals("keep"),"reset preserves unrelated item data");h.succeed();
 }
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=24000)
 public static void usedManualPointDoesNotLockNormalExtension(GameTestHelper h){
  var l=h.getLevel();var d=RoadData.get(l);int x=194000,z=194000;
  var a=road(h,x,z,100,0,220,Style.O1_ONE);var b=road(h,x+180,z+70,100,0,220,Style.O1_ONE);
  var p=manual(h,a,40,0);var q=manual(h,b,20,0);var r=ramp(h,a,p,b,q,LanePoints.Path.DIRECT,false,false);
  var end=Revision32GameTests.marker(h,x+140,220,z,-90);var continuation=d.connect(l,null,a.b(),end,a.settings(),null);
  check(h,d.index.roads.containsKey(continuation.id()),"used manual point does not lock normal continuation");
  check(h,LaneTopology.point(current(d,a),p.id()).origin()==LanePoints.Origin.MANUAL,"normal continuation retains used manual identity");
  check(h,LaneTopology.metadata(current(d,r)).link().from().equals(LanePoints.Ref.lane(a.id(),p.id())),"normal continuation preserves actual ramp reference");
  check(h,LaneTopology.metadata(current(d,a)).points().stream().noneMatch(v->v.origin()==LanePoints.Origin.AUTOMATIC_END),"normal continuation removes only unused automatic end points");
  h.succeed();
 }
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=24000)
 public static void automaticPermissionsAndNormalContinuity(GameTestHelper h){var l=h.getLevel();var d=RoadData.get(l);var ab=road(h,180000,180000,100,0,220,Style.O4_YELLOW);check(h,LaneTopology.metadata(current(d,ab)).points().size()==8,"four lanes at both real free ends");var b=ab.b();var c=Revision32GameTests.marker(h,180200,220,180000,-90);var manual=manual(h,current(d,ab),100,2);var bc=d.connect(l,null,b,c,ab.settings(),null);check(h,LaneTopology.metadata(current(d,ab)).points().size()==5,"B autos removed, manual remains");check(h,LaneTopology.metadata(current(d,bc)).points().size()==4,"BC only C free");var auto=LaneTopology.metadata(current(d,ab)).points().stream().filter(LanePoints.Point::automatic).findFirst().orElseThrow();var edit=LanePointTool.payload(d,current(d,ab),auto);edit.putBoolean("Delete",true);boolean denied=false;try{LanePointTool.edit(l,null,edit);}catch(IllegalArgumentException e){denied=true;}check(h,denied,"automatic delete rejected server-side");edit=LanePointTool.payload(d,current(d,ab),manual);edit.putInt("Lane",0);LanePointTool.edit(l,null,edit);var changed=LaneTopology.point(current(d,ab),manual.id());check(h,changed.lane()==0&&LanePoints.lane(current(d,ab).mesh(),changed).direction().dot(LanePoints.lane(ab.mesh(),100,2).direction())<-.99,"manual switch into reverse direction");d.remove(l,null,bc.id());check(h,LaneTopology.metadata(current(d,ab)).points().size()==9,"free-end autos restored alongside manual");h.succeed();}
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=24000)
 public static void builtReferencesLocksReloadDeletion(GameTestHelper h){var l=h.getLevel();var d=RoadData.get(l);var a=road(h,181000,181000,0,-80,220,Style.O1_ONE);var b=road(h,181020,180820,0,-100,226,Style.O1_ONE);var p=LaneTopology.metadata(current(d,a)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_END).findFirst().orElseThrow();var q=LaneTopology.metadata(current(d,b)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_START).findFirst().orElseThrow();var r=ramp(h,a,p,b,q,LanePoints.Path.DIRECT,false,false);check(h,r.assembly()==null&&RoadProfile.catalog(r.settings().style()).lanes()==1,"connector independent single lane ordinary");check(h,!d.index.roads.get(r.id()).cells.isEmpty(),"actual collision installed");var before=d.save(new CompoundTag());var c=Revision32GameTests.marker(h,181000,220,180880,180);boolean blocked=false;try{d.connect(l,null,a.b(),c,a.settings(),null);}catch(IllegalArgumentException e){blocked=true;}check(h,blocked&&before.equals(d.save(new CompoundTag())),"used end normal connection rolls back");var loaded=RoadData.load(before);check(h,LaneTopology.metadata(loaded.index.roads.get(r.id()).record).link().equals(LaneTopology.metadata(r).link()),"links persist");check(h,LaneTopology.references(LaneTopology.records(loaded).values(),LanePoints.Ref.lane(a.id(),p.id())).size()==1,"occupancy reconstructs from built roads");d.remove(l,null,r.id());check(h,LaneTopology.references(LaneTopology.records(d).values(),LanePoints.Ref.lane(a.id(),p.id())).isEmpty(),"deleting ramp releases point");d.connect(l,null,a.b(),c,a.settings(),null);check(h,LaneTopology.metadata(current(d,a)).points().stream().noneMatch(v->v.id().equals(p.id())),"unlocked end can extend");h.succeed();}
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void manualEditSecondaryOutgoingIncomingAndCascade(GameTestHelper h){var l=h.getLevel();var d=RoadData.get(l);var a=road(h,182000,182100,0,-160,230,Style.H2_ONE);var b=road(h,182028,181870,0,-180,230,Style.H2_ONE);var p=manual(h,a,80,0);var q=manual(h,b,90,0);var r=ramp(h,a,p,b,q,LanePoints.Path.DIRECT,false,false);check(h,r.settings().style()==Style.H1_ONE,"highway identity follows source");var oldStart=r.mesh().first().center();var switchLane=LanePointTool.payload(d,current(d,a),p);switchLane.putInt("Lane",1);LanePointTool.edit(l,null,switchLane);r=current(d,r);check(h,r.mesh().first().center().distance(oldStart)>3,"used manual lane switch physically rebuilds its ramp");var rp=manual(h,r,r.mesh().length()*.55,0);var c=road(h,181910,181710,0,-140,230,Style.O1_ONE);var cp=manual(h,c,70,0);var branch=ramp(h,r,rp,c,cp,LanePoints.Path.DIRECT,false,false);var feeder=road(h,182070,182130,0,-80,230,Style.O1_ONE);var fp=manual(h,feeder,40,0);var incoming=ramp(h,feeder,fp,current(d,r),rp,LanePoints.Path.DIRECT,false,false);check(h,d.index.roads.containsKey(branch.id())&&d.index.roads.containsKey(incoming.id()),"new ramp supports actual outgoing and incoming ramps");check(h,LaneTopology.references(LaneTopology.records(d).values(),LanePoints.Ref.lane(r.id(),rp.id())).size()==2,"incoming and outgoing references both count at the same point");var snapshot=d.save(new CompoundTag());var edit=LanePointTool.payload(d,current(d,r),rp);edit.putBoolean("Delete",true);boolean denied=false;try{LanePointTool.edit(l,null,edit);}catch(IllegalArgumentException e){denied=true;}check(h,denied&&snapshot.equals(d.save(new CompoundTag())),"used manual delete requires explicit reviewed dependencies");edit.put("ConfirmDependencies",edit.getList("Dependencies",Tag.TAG_STRING).copy());LanePointTool.edit(l,null,edit);check(h,d.index.roads.containsKey(r.id())&&!d.index.roads.containsKey(branch.id())&&!d.index.roads.containsKey(incoming.id()),"confirmed cascade removes exact dependents only");h.succeed();}
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void realRightLoopExtraAndRollback(GameTestHelper h){var d=RoadData.get(h.getLevel());var a=road(h,184000,184200,0,-80,220,Style.O1_ONE);var b=road(h,184100,184020,100,0,220,Style.O1_ONE);var p=LaneTopology.metadata(current(d,a)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_END).findFirst().orElseThrow();var q=manual(h,b,40,0);var right=ramp(h,a,p,b,q,LanePoints.Path.RIGHT,false,false);check(h,right.mesh().length()>100,"real right roadway");d.remove(h.getLevel(),null,right.id());var leftHost=road(h,183860,184020,-100,0,228,Style.O1_ONE);var lp=LaneTopology.metadata(current(d,leftHost)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_START).findFirst().orElseThrow();var loop=ramp(h,a,p,leftHost,lp,LanePoints.Path.LEFT_LOOP,false,false);check(h,loop.mesh().length()>300,"left is long-turn loop");check(h,loop.structures().stream().anyMatch(part->part.pier()),"loop uses actual foundation supports");check(h,loop.structures().stream().noneMatch(part->RoadInteractions.selfSupportBlocked(part,loop.mesh())),"loop supports cannot obstruct its own lower roadway");check(h,LaneTopology.metadata(current(d,a)).openings().size()==1,"actual loop opens source furniture");var before=d.save(new CompoundTag());boolean fail=false;try{var link=new LanePoints.Link(LanePoints.Ref.lane(a.id(),p.id()),LanePoints.Ref.lane(a.id(),p.id()),LanePoints.Options.DEFAULT,null);}catch(IllegalArgumentException e){fail=true;}check(h,fail&&before.equals(d.save(new CompoundTag())),"invalid request leaves world identical");h.succeed();}
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void realRoundaboutIncomingArm(GameTestHelper h){var l=h.getLevel();var d=RoadData.get(l);int x=186000,z=186000;var center=Revision32GameTests.marker(h,x,220,z,0);var spec=new JunctionSpec(new V(x+.5,220,z+.5),JunctionSpec.Kind.ROUNDABOUT,false,6,12,1,4,1,JunctionSpec.Control.YIELD,20,3,1,0,true,true,List.of());AutoJunctions.createRing(l,null,center,spec);var group=d.junctions.keySet().stream().filter(id->d.junctions.get(id).getBoolean("GeneratedRing")&&JunctionCodec.read(d.junctions.get(id).getCompound("Spec")).center().equals(spec.center())).findFirst().orElseThrow();var a=road(h,x-20,z+250,0,-100,220,Style.O1_ONE);var p=manual(h,a,50,0);V mouth=RampJunctions.mouth(d,group,p.position(),a.settings());var link=new LanePoints.Link(LanePoints.Ref.lane(a.id(),p.id()),LanePoints.Ref.junction(group),LanePoints.Options.DEFAULT,mouth);var r=LaneRamps.generate(d,LaneTopology.records(d),UUID.randomUUID(),new UUID(0,0),link);LaneRamps.build(d,l,null,r);var after=JunctionCodec.read(d.junctions.get(group).getCompound("Spec"));check(h,after.arms().size()==1&&after.arms().get(0).incoming()==1,"real incoming roundabout arm");check(h,d.index.roads.values().stream().anyMatch(b->group.equals(b.record.assembly())&&b.record.junction().get().arm()==0),"actual arm pieces exist");check(h,current(d,r).mesh().last().center().distance(after.arms().get(0).endpoint().position())<1e-6,"ramp meets actual junction mouth");d.remove(l,null,r.id());check(h,JunctionCodec.read(d.junctions.get(group).getCompound("Spec")).arms().isEmpty(),"deleting connector removes incoming arm");h.succeed();}
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void ordinaryJunctionAndConfirmedCascade(GameTestHelper h){var l=h.getLevel();var d=RoadData.get(l);int x=188000,z=188000;var center=Revision32GameTests.marker(h,x,220,z,0);var n=Revision32GameTests.marker(h,x,220,z-60,0);var south=Revision32GameTests.marker(h,x,220,z+60,180);var east=Revision32GameTests.marker(h,x+60,220,z,90);var payload=Junctions.payload(l,null,new long[]{center.asLong(),n.asLong(),south.asLong(),east.asLong()},null);Junctions.build(l,null,payload);UUID group=d.junctions.keySet().stream().filter(id->JunctionCodec.read(d.junctions.get(id).getCompound("Spec")).center().distance(RoadData.requireNode(l,center,null).node().position())<.01).findFirst().orElseThrow();var outside=Revision32GameTests.marker(h,x,220,z-140,0);var exterior=d.connect(l,null,outside,n,Settings.defaults().structure(Structure.GROUND),null);check(h,LaneTopology.metadata(current(d,exterior)).points().size()==2,"one junction end leaves only two automatic points at free end");var farCenter=Revision32GameTests.marker(h,x,220,z-200,0);var farNorth=Revision32GameTests.marker(h,x,220,z-260,0);var farEast=Revision32GameTests.marker(h,x+60,220,z-200,90);Junctions.build(l,null,Junctions.payload(l,null,new long[]{farCenter.asLong(),outside.asLong(),farNorth.asLong(),farEast.asLong()},null));check(h,LaneTopology.metadata(current(d,exterior)).points().isEmpty(),"both junction ends generate no automatic points");var a=road(h,x-260,z,100,0,220,Style.O1_ONE);var p=LaneTopology.metadata(current(d,a)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_END).findFirst().orElseThrow();var link=new LanePoints.Link(LanePoints.Ref.lane(a.id(),p.id()),LanePoints.Ref.junction(group),LanePoints.Options.DEFAULT,RampJunctions.mouth(d,group,p.position(),a.settings()));var r=LaneRamps.generate(d,LaneTopology.records(d),UUID.randomUUID(),new UUID(0,0),link);LaneRamps.build(d,l,null,r);check(h,JunctionCodec.read(d.junctions.get(group).getCompound("Spec")).arms().size()==4,"ordinary junction gains actual fourth arm");var edit=Junctions.payload(l,null,new long[0],group);Junctions.build(l,null,edit);check(h,d.index.roads.containsKey(r.id()),"junction rebuild retains connector and arm");var delete=new CompoundTag();delete.putUUID("Id",group);LaneDeletes.junctionPayload(d,group,delete);var before=d.save(new CompoundTag());boolean refused=false;try{LaneDeletes.removeJunction(l,null,delete);}catch(IllegalArgumentException e){refused=true;}check(h,refused&&before.equals(d.save(new CompoundTag())),"junction deletion requires exact cascade confirmation");delete.put("ConfirmDependencies",delete.getList("Dependencies",Tag.TAG_STRING).copy());LaneDeletes.removeJunction(l,null,delete);check(h,!d.junctions.containsKey(group)&&!d.index.roads.containsKey(r.id())&&d.index.roads.containsKey(a.id()),"confirmed junction cascade preserves external source");h.succeed();}
 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void sharedEndpointMigratesUsedLanePoint(GameTestHelper h){var l=h.getLevel();var d=RoadData.get(l);int x=190000,z=190000;var ab=road(h,x,z,100,0,220,Style.O2_YELLOW);var c=Revision32GameTests.marker(h,x+200,220,z,-90);var bc=d.connect(l,null,ab.b(),c,ab.settings(),null);var p=manual(h,bc,25,1);var target=road(h,x+260,z+25,120,0,220,Style.O1_ONE);var q=manual(h,target,60,0);var r=ramp(h,bc,p,target,q,LanePoints.Path.DIRECT,false,false);var marker=RoadData.requireNode(l,ab.b(),null);Node moved=new Node(new V(x+150.5,marker.node().position().y(),z+.5),-90,0);var built=new ArrayList<RoadIndex.Built>();var removed=new HashSet<UUID>();SharedRoadEndpoints.stage(d,l,null,ab.b(),moved,built,removed);d.replaceAssembly(l,null,built,removed,Set.of(ab.a(),c),List.of(new RoadData.NodeMove(ab.b(),RampJunctions.at(moved.position()),moved,marker.saveWithoutMetadata())));check(h,LaneTopology.metadata(current(d,r)).link().from().road().equals(ab.id()),"used point migrates ref to actual new owner");var actual=LaneTopology.point(current(d,ab),p.id());check(h,actual.position().distance(p.position())<.01,"shared move keeps same lane location");check(h,current(d,r).mesh().first().center().distance(actual.position())<.01,"dependent ramp remains attached to actual lane point");h.succeed();}

 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void expandedPortsAndStrictTypes(GameTestHelper h){var l=h.getLevel();var d=RoadData.get(l);var a=road(h,192000,192000,0,-180,220,Style.O1_ONE);var b=road(h,192030,191740,0,-180,220,Style.O1_ONE);var p=manual(h,a,50,0);var q=manual(h,b,110,0);var r=ramp(h,a,p,b,q,LanePoints.Path.DIRECT,true,true);check(h,r.mesh().first().center().distance(p.position())<.01&&r.mesh().last().center().distance(q.position())<.01,"extra paths still start and end at exact selected lanes");check(h,LaneTopology.metadata(r).link().options().sourceExtra()&&LaneTopology.metadata(r).link().options().targetExtra(),"both expansion options persist");var fakeAttached=new RoadAttachments.Point(UUID.randomUUID(),p.position(),p.position(),false);a=current(d,a);d.updatePointMetadata(l,null,a,new RoadAttachments.Data(List.of(fakeAttached),List.of()));boolean rejected=false;try{LaneRamps.host(LaneTopology.records(d),LanePoints.Ref.lane(a.id(),fakeAttached.id()));}catch(IllegalArgumentException e){rejected=true;}check(h,rejected,"coincident attached point ID cannot substitute for real lane point");var tagged=current(d,a).alignment(UUID.randomUUID(),current(d,a).mesh());var isolated=new LinkedHashMap<>(LaneTopology.records(d));isolated.put(a.id(),tagged);rejected=false;try{LaneRamps.host(isolated,LanePoints.Ref.lane(a.id(),p.id()));}catch(IllegalArgumentException e){rejected=true;}check(h,rejected,"interchange identity is independently rejected");for(var bridge:RoadInfrastructure.Bridge.values()){var settings=a.settings().structure(Structure.BRIDGE).options(a.settings().options().infrastructure(a.settings().options().infrastructure().bridge(bridge)));check(h,LanePoints.supported(settings)==(bridge==RoadInfrastructure.Bridge.STANDARD||bridge==RoadInfrastructure.Bridge.BEAM||bridge==RoadInfrastructure.Bridge.OVERPASS),"exact supported bridge set: "+bridge);}check(h,!LanePoints.supported(a.settings().structure(Structure.TUNNEL)),"tunnel remains unsupported");h.succeed();}

 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void flexibleLandingEditableRampAndPersistence(GameTestHelper h){
  var l=h.getLevel();var data=RoadData.get(l);var a=road(h,201000,201000,0,-220,220,Style.O2_ONE);var b=road(h,201030,200700,0,-180,220,Style.O2_ONE);
  var p=manual(h,a,40,0);var q=LaneTopology.metadata(current(data,b)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_START&&v.lane()==0).findFirst().orElseThrow();
  var r=ramp(h,a,p,b,q,LanePoints.Path.DIRECT,true,true);var link=LaneTopology.metadata(r).link();
  check(h,link.targetOffset()>=64&&link.targetOffset()<=LaneRamps.targetReach(link.options()),"search moves actual landing ahead of B to fit a full auxiliary lane");
  check(h,link.to().point().equals(q.id())&&LaneTopology.point(current(data,b),q.id()).position().distance(q.position())<1e-7,"landing search does not move or replace selected target marker");
  check(h,r.mesh().last().center().distance(LaneRamps.targetPort(current(data,b),q,link.targetOffset()).position())<1e-6,"actual endpoint uses persisted signed lane offset");
  var point=manual(h,r,r.mesh().length()*.5,0);r=current(data,r);var signature=r.header().hashCode();
  var settings=r.settings().options(r.settings().options().hideArrows(true));var command=new CompoundTag();command.putUUID("Id",r.id());command.putInt("Signature",signature);command.put("Settings",RoadRecord.writeSettings(settings));
  LaneRamps.editRoad(l,null,command);r=current(data,r);check(h,r.settings().options().hideArrows()&&LaneTopology.point(r,point.id())!=null,"road editor saves options and retains ramp and manual point identity without NodeEntity endpoints");
  var changed=new LanePoints.Link(link.from(),link.to(),new LanePoints.Options(LanePoints.Path.DIRECT,false,true,28,32),null,link.targetOffset());
  var next=LaneRamps.generate(data,LaneTopology.records(data),r.id(),r.owner(),changed);LaneRamps.build(data,l,null,next);r=current(data,r);
  check(h,!LaneTopology.metadata(r).link().options().sourceExtra()&&r.settings().options().hideArrows(),"connector editing changes path settings without losing road-editor options");
  check(h,LaneTopology.point(r,point.id()).position().distance(LanePoints.lane(r.mesh(),LaneTopology.point(r,point.id())).position())<1e-6,"retained manual point is reconciled to edited alignment");
  var saved=data.save(new CompoundTag());var reload=RoadData.load(saved);var restored=reload.index.roads.get(r.id()).record;
  check(h,saved.getInt("Version")==34&&LaneTopology.metadata(restored).equals(LaneTopology.metadata(r)),"offset, options and point IDs survive world reload");
  check(h,!LaneTopology.needsRefresh(reload.index.roads.values()),"shifted landing does not cause endless dependency refresh");
  var old=LanePointCodec.link(link);old.remove("TargetOffset");check(h,LanePointCodec.link(old).targetOffset()==0,"older links without offset remain exact B at load");
  var snapshot=data.save(new CompoundTag());command.putInt("Signature",r.header().hashCode());command.put("Settings",RoadRecord.writeSettings(r.settings().structure(Structure.TUNNEL)));boolean denied=false;try{LaneRamps.editRoad(l,null,command);}catch(IllegalArgumentException e){denied=true;}check(h,denied&&snapshot.equals(data.save(new CompoundTag())),"invalid road edit is atomic");h.succeed();
 }

 @GameTest(template="empty",templateNamespace="splineroads_lane_v2",timeoutTicks=30000)
 public static void crossingsUseActualOverpassAndUnderpass(GameTestHelper h){
  var l=h.getLevel();var d=RoadData.get(l);int x=203000,z=203000;
  for(boolean under:List.of(false,true)){
   var a=road(h,x,z,0,60,210,Style.O1_ONE);var b=road(h,x,z+380,0,60,210,Style.O1_ONE);
   var p=LaneTopology.metadata(current(d,a)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_END).findFirst().orElseThrow();var q=LaneTopology.metadata(current(d,b)).points().stream().filter(v->v.origin()==LanePoints.Origin.AUTOMATIC_START).findFirst().orElseThrow();
   var crossing=road(h,x-80,z+220,160,0,under?214:210,Style.O2_ONE);
   var r=ramp(h,a,p,b,q,LanePoints.Path.DIRECT,false,false);var at=RoadQueries.horizontal(r.mesh(),crossing.mesh().samples().get(crossing.mesh().samples().size()/2).center()).sample().center();
   check(h,under?at.y()<p.position().y()-1:at.y()>p.position().y()+5,"automatic crossing chooses a real "+(under?"underpass":"overpass"));
   check(h,Math.abs(at.y()-crossing.mesh().first().center().y())>=5,"actual crossing retains full deck clearance");
   check(h,r.mesh().first().center().distance(p.position())<1e-6&&r.mesh().last().center().distance(q.position())<1e-6,"grade separation preserves source and target lanes");
   var saved=RoadData.load(d.save(new CompoundTag())).index.roads.get(r.id()).record;check(h,saved.alignment().equals(r.alignment()),"crossing elevation is stored as real alignment");x+=1000;
  }h.succeed();
 }

}
