package net.minecraft.nbt;
import java.util.*;
/** TEST ONLY: typed in-memory map, NOT Minecraft NBT encoding. */
public class CompoundTag implements Tag {
 private final Map<String,Object> values=new HashMap<>();
 public void put(String k,Tag v){values.put(k,v);}public void putInt(String k,int v){values.put(k,v);}public void putLong(String k,long v){values.put(k,v);}public void putDouble(String k,double v){values.put(k,v);}public void putBoolean(String k,boolean v){values.put(k,v);}public void putString(String k,String v){values.put(k,v);}public void putUUID(String k,UUID v){values.put(k,v);}public void putByteArray(String k,byte[] v){values.put(k,v.clone());}public void putIntArray(String k,int[] v){values.put(k,v.clone());}
 public void putIntArray(String k,java.util.List<Integer> values){putIntArray(k,values.stream().mapToInt(Integer::intValue).toArray());}
 public int getInt(String k){return values.get(k) instanceof Number n?n.intValue():0;}public long getLong(String k){return values.get(k) instanceof Number n?n.longValue():0;}public double getDouble(String k){return values.get(k) instanceof Number n?n.doubleValue():0;}public boolean getBoolean(String k){return Boolean.TRUE.equals(values.get(k));}public String getString(String k){return values.get(k) instanceof String s?s:"";}public UUID getUUID(String k){if(!(values.get(k) instanceof UUID))throw new IllegalArgumentException("missing UUID "+k);return (UUID)values.get(k);}public CompoundTag getCompound(String k){return values.get(k) instanceof CompoundTag c?c:new CompoundTag();}public ListTag getList(String k,int type){return values.get(k) instanceof ListTag l?l:new ListTag();}public byte[] getByteArray(String k){return values.get(k) instanceof byte[] a?a.clone():new byte[0];}public int[] getIntArray(String k){return values.get(k) instanceof int[] a?a.clone():new int[0];}
 public void putLongArray(String k,long[] v){values.put(k,v.clone());} public long[] getLongArray(String k){return values.get(k) instanceof long[] a?a.clone():new long[0];}
 public boolean contains(String k){return values.containsKey(k);}public boolean contains(String k,int type){return contains(k);}public boolean hasUUID(String k){return values.get(k) instanceof UUID;}public void remove(String k){values.remove(k);}public boolean isEmpty(){return values.isEmpty();}
 public CompoundTag copy(){var t=new CompoundTag();for(var e:values.entrySet()){var v=e.getValue();t.values.put(e.getKey(),v instanceof Tag a?a.copy():v instanceof byte[] a?a.clone():v instanceof int[] a?a.clone():v instanceof long[] a?a.clone():v);}return t;}
 @Override public boolean equals(Object o){if(!(o instanceof CompoundTag t)||!values.keySet().equals(t.values.keySet()))return false;for(String k:values.keySet())if(!Objects.deepEquals(values.get(k),t.values.get(k)))return false;return true;}
 @Override public int hashCode(){int h=0;for(var e:values.entrySet()){Object v=e.getValue();int a=v instanceof byte[] b?Arrays.hashCode(b):v instanceof int[] b?Arrays.hashCode(b):v instanceof long[] b?Arrays.hashCode(b):v.hashCode();h+=e.getKey().hashCode()^a;}return h;}
}